trigger:
- master

variables:
- group: stayapp-variable-group

stages:
- stage: Production
  jobs:
  - job: build_application
    displayName: Validate PowerShell Scripts
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'aws-service-connection'
        regionName: 'ap-southeast-2'
        sourceImageName: 'stayapp'
        repositoryName: '$(ContainerRegistry)'

  - job: deploy_infrastructure
    displayName: Validate PowerShell Scripts
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.12.3'

    - task: TerraformTaskV1@0
      displayName: 'Terraform init'
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceAWS: 'aws-terraform-service-connection'
        backendAWSBucketName: 'stayapp-terraform'
        backendAWSKey: 'terraform'
