trigger:
- master

variables:
- group: stayapp-variable-group
- name: AWS_SERVICE_CONNECTION
  value: aws-service-connection
- name: AWS_TERRAFORM_SERVICE_CONNECTION
  value: aws-terraform-service-connection

stages:
- stage: Production
  jobs:
  - job: build_application
    displayName: Validate PowerShell Scripts
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerComposeFile: 'docker-compose.yml'
        action: 'Build services'

    - task: ECRPushImage@1
      inputs:
        awsCredentials: '$(AWS_SqERVICE_CONNECTION)'
        regionName: 'ap-southeast-2'
        imageSource: 'imagename'
        sourceImageName: 'staypp'
        repositoryName: 'stayapp'

  - job: deploy_infrastructure
    displayName: Validate PowerShell Scripts
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.12.3'

    - task: TerraformTaskV1@0
      displayName: 'Terraform init'
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceAWS: '$(AWS_TERRAFORM_SERVICE_CONNECTION)'
        backendAWSBucketName: 'stayapp-terraform'
        backendAWSKey: 'terraform'

    - task: TerraformTaskV1@0
      inputs:
        provider: 'aws'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceNameAWS: '$(AWS_TERRAFORM_SERVICE_CONNECTION)'

    - task: TerraformTaskV1@0
      inputs:
        provider: 'aws'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceNameAWS: '$(AWS_TERRAFORM_SERVICE_CONNECTION)'
