version: '3'

services:
  stayapp:
    image: stayapp:${STAYAPP_TAG:-latest}
    restart: always
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --log-level debug --reload --proxy-headers
    env_file: .env
    build:
      context: .
    ports:
      - 8000:8000
      - 5678:5678
