version: '3'

services:
  stayapp:
    image: stayapp:${STAYAPP_TAG:-latest}
    volumes:
      - ./app:/app
    environment:
      - FLASK_DEBUG=1
    build:
      context: .
    ports:
      - 80:80
