version: '3'

services:
  stayapp:
    image: stayapp:${STAYAPP_TAG:-latest}
    restart: on-failure
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --log-level debug --reload
    environment:
      ENVIRONMENT: development
    build:
      context: .
    ports:
      - 8000:8000
      - 8080:8080
