apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stayapp-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: stayapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stayapp
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: stayapp-flask-server
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 384Mi
          requests:
            cpu: 25m
            memory: 128Mi
