apiVersion: v1
kind: Service
metadata:
  name: stayapp-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: stayapp
  type: LoadBalancer
  loadBalancerIP: '35.244.74.9'
