trigger:
- master

stages:
- stage: Production
  jobs:
  - job: validate
    displayName: Validate PowerShell Scripts
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.12.3'

    - task: TerraformTaskV1@0
      displayName: 'Terraform init'
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceAWS: 'rmit-cloud-computing-aws-terraform-service-connection'
        backendAWSBucketName: 'stayapp-terraform'
        backendAWSKey: 'terraform'
